PL/Controllers/AdminController.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using BL.DTO;
using BL.DTO.UserAccount;
using BL.Facades;
using BL.Filters;
using BL.Utilities.AccountPolicy;
using PL.Models;
using X.PagedList;
using ActionResult = System.Web.Mvc.ActionResult;
using Controller = System.Web.Mvc.Controller;

namespace PL.Controllers
{
    [Authorize(Roles = Claims.Admin)]
    public class AdminController : Controller
    {
        private readonly string filterSessionKey = "filterforasflasjgfkjh";

        public LibraryFacade LibraryFacade { get; set; }

        public UserFacade UserFacade { get; set; }

        [Authorize(Roles = Claims.AuthenticatedUsers)]
        public ActionResult Settings()
        {
            UserPasswordDTO model = new UserPasswordDTO()
            {
                Username = User.Identity.Name
            };
            return View("ChangePassword", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Settings(UserPasswordDTO model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    UserFacade.ChangePassword(model);
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View("ChangePassword");
        }

        public ActionResult Promote(int page = 1)
        {
            var filter = Session[filterSessionKey] as VipCodeFilter ?? new VipCodeFilter();

            VipCodesListQueryResultsDTO result = UserFacade.ListCodes(filter, page);

            VipCodeListViewModel model = InitNewModel(result, filter);

            return View("List", model);
        }


        [HttpPost]
        public ActionResult Promote(VipCodeListViewModel model)
        {
            
            Session[filterSessionKey] = model.Filter;

            var result = UserFacade.ListCodes(model.Filter);

            VipCodeListViewModel newModel = InitNewModel(result, model.Filter);

            return View("List", newModel);
        }


        private VipCodeListViewModel InitNewModel(VipCodesListQueryResultsDTO result, VipCodeFilter filter)
        {
            return new VipCodeListViewModel
            {
                Filter = filter,
                Codes = new StaticPagedList<VipCodesDTO>(result.ResultsPage, result.RequestedPage, LibraryFacade.PageSize, result.TotalResultCount),
            };
        }

        public ActionResult ClearFilter()
        {
            Session[filterSessionKey] = null;
            return RedirectToAction(nameof(Promote));
        }

        public ActionResult Delete(int id)
        {
            UserFacade.RemoveVip(id);
            return RedirectToAction(nameof(Promote));
        }

        public ActionResult Upgrade(Guid id)
        {
            var vipCode = UserFacade.GetCodeById(id);
            UserFacade.PromoteUser(id, false, true);
            UserFacade.RemoveVip(vipCode.ID);
            return RedirectToAction(nameof(Promote));
        }
    }
}

PL/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using BL.DTO;
using BL.DTO.Album;
using BL.Facades;
using BL.Filters;
using BL.Utilities.AccountPolicy;
using PL.Models;
using X.PagedList;
using ActionResult = System.Web.Mvc.ActionResult;
using Controller = System.Web.Mvc.Controller;


namespace PL.Controllers
{
    [Authorize(Roles = Claims.AuthenticatedUsers)]
    public class AlbumController : Controller
    {
        private readonly string filterSessionKey = "filteralbum";

        public LibraryFacade LibraryFacade { get; set; }

        public UserFacade UserFacade { get; set; }

        public ActionResult Index(int page = 1)
        {
            AlbumFilter filter = Session[filterSessionKey] as AlbumFilter ?? new AlbumFilter();

            AlbumListQueryResultDTO result = LibraryFacade.GetAlbums(filter, page);

            AlbumListViewModel model = InitNewAlbum(result, filter);

            return View("List", model);
        }


        [HttpPost]
        public ActionResult Index(AlbumListViewModel model)
        {
            Session[filterSessionKey] = model.Filter;

            var result = LibraryFacade.GetAlbums(model.Filter);

            var newModel = InitNewAlbum(result, model.Filter);

            return View("List", newModel);
        }

        public ActionResult ClearFilter()
        {
            Session[filterSessionKey] = null;
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Details(int id)
        {
            var model = LibraryFacade.GetAlbum(id);
            string result = "";
            foreach (var song in LibraryFacade.GetAllSongs())
            {
                if (song.AlbumPId == id)
                {
                    result += song.Name + ", ";
                }
            }
            if (result.Length > 2)
            {
                result = result.Substring(0, result.Length - 2);
                ViewBag.Songs = result;
            }
            else
            {
                ViewBag.Songs = "";
            }
            if (model.Creator == UserFacade.GetGuidByEmail(User.Identity.Name))
            {
                return View("Details", model);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var model = LibraryFacade.GetAlbum(id);
            if (model.Creator == UserFacade.GetGuidByEmail(User.Identity.Name))
            {
                LibraryFacade.DeleteAlbum(id);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            InitBasics();
            return View("Create", new AlbumDTO());
        }

        private void InitBasics()
        {
            var filter = new ArtistFilter
            {
                CreatorId = UserFacade.GetGuidByEmail(User.Identity.Name)
            };
            ViewBag.Artists = LibraryFacade.GetArtistBasicsByFilter(filter);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AlbumDTO model)
        {
            model.Creator = UserFacade.GetGuidByEmail(User.Identity.Name);
            if (ModelState.IsValid)
            {
                try
                {
                    LibraryFacade.CreateAlbum(model);
                    return RedirectToAction("Index");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            InitBasics();
            return View("Create", model);
        }

        public ActionResult Edit(int id)
        {
            var model = LibraryFacade.GetAlbum(id);
            if (model.Creator == UserFacade.GetGuidByEmail(User.Identity.Name))
            {
                InitBasics();
                return View("Edit", model);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AlbumDTO model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    LibraryFacade.EditAlbum(model);
                    return RedirectToAction("Index");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            InitBasics();
            return RedirectToAction("Edit", model);
        }

        private AlbumListViewModel InitNewAlbum(AlbumListQueryResultDTO result, AlbumFilter filter)
        {
            return new AlbumListViewModel
            {
                Albums = new StaticPagedList<AlbumDTO>(result.ResultsPage, result.RequestedPage, LibraryFacade.PageSize, result.TotalResultCount),
                Filter = filter
            };
        }
    }
}

PL/Controllers/EventController.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using BL.DTO;
using BL.DTO.Event;
using BL.Facades;
using BL.Filters;
using BL.Utilities.AccountPolicy;
using PL.Models;
using X.PagedList;
using ActionResult = System.Web.Mvc.ActionResult;
using Controller = System.Web.Mvc.Controller;

namespace PL.Controllers
{
    [Authorize(Roles = Claims.Vips)]
    public class EventController : Controller
    {
        private readonly string filterSessionKey = "filterevent";

        public PremiumFacade PremiumFacade { get; set; }
        public LibraryFacade LibraryFacade { get; set; }

        public UserFacade UserFacade { get; set; }

        public ActionResult Index(int page = 1)
        {
            EventFilter filter = Session[filterSessionKey] as EventFilter ?? new EventFilter();

            EventListQueryResultDTO result = PremiumFacade.GetEvents(filter, page);

            EventListViewModel model = InitNewEvent(result, filter);

            return View("List", model);
        }


        [HttpPost]
        public ActionResult Index(EventListViewModel model)
        {
            Session[filterSessionKey] = model.Filter;

            var result = PremiumFacade.GetEvents(model.Filter);

            var newModel = InitNewEvent(result, model.Filter);

            return View("List", newModel);
        }

        public ActionResult ClearFilter()
        {
            Session[filterSessionKey] = null;
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Details(int id)
        {
            var model = PremiumFacade.GetEvent(id);
            if (model.Creator == UserFacade.GetGuidByEmail(User.Identity.Name))
            {
                return View("Details", model);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var model = PremiumFacade.GetEvent(id);
            if (model.Creator == UserFacade.GetGuidByEmail(User.Identity.Name))
            {
                PremiumFacade.DeleteEvent(id);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            InitBasics();
            return View("Create", new EventDTO());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EventDTO model)
        {
            model.Creator = UserFacade.GetGuidByEmail(User.Identity.Name);
            if (model.ArtistPId != null) { model.Artist = LibraryFacade.GetArtist(model.ArtistPId.Value);}
            if (ModelState.IsValid)
            {
                try
                {
                    PremiumFacade.CreateEvent(model);
                    return RedirectToAction("Index");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            InitBasics();
            return View("Create", model);
        }

        private void InitBasics()
        {
            var filter = new ArtistFilter
            {
                CreatorId = UserFacade.GetGuidByEmail(User.Identity.Name)
            };
            ViewBag.Artists = LibraryFacade.GetArtistBasicsByFilter(filter);
        }

        public ActionResult Edit(int id)
        {
            var model = PremiumFacade.GetEvent(id);
            if (model.Creator == UserFacade.GetGuidByEmail(User.Identity.Name))
            {
                InitBasics();
                return View("Edit", model);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EventDTO model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    PremiumFacade.EditEvent(model);
                    return RedirectToAction("Index");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            InitBasics();
            return RedirectToAction("Edit", model);
        }


        private EventListViewModel InitNewEvent(EventListQueryResultDTO result, EventFilter filter)
        {
            return new EventListViewModel
            {
                Events = new StaticPagedList<EventDTO>(result.ResultsPage, result.RequestedPage, PremiumFacade.PageSize, result.TotalResultCount),
                Filter = filter
            };
        }
    }
}

PL/Controllers/SongController.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using BL.DTO;
using BL.DTO.Song;
using BL.Facades;
using BL.Filters;
using BL.Utilities.AccountPolicy;
using PL.Models;
using X.PagedList;

namespace PL.Controllers
{
    [Authorize(Roles = Claims.AuthenticatedUsers)]
    public class SongController : Controller
    {
        private readonly string filterSessionKey = "filtersong";

        public LibraryFacade LibraryFacade { get; set; }

        public UserFacade UserFacade { get; set; }

        public ActionResult Index(int page = 1)
        {
            SongFilter filter = Session[filterSessionKey] as SongFilter ?? new SongFilter();

            SongListQueryResultDTO result = LibraryFacade.GetSongs(filter, page);

            SongListViewModel model = InitNewSong(result, filter);

            return View("List", model);
        }


        [HttpPost]
        public ActionResult Index(SongListViewModel model)
        {
            Session[filterSessionKey] = model.Filter;

            var result = LibraryFacade.GetSongs(model.Filter);

            var newModel = InitNewSong(result, model.Filter);

            return View("List", newModel);
        }

        public ActionResult ClearFilter()
        {
            Session[filterSessionKey] = null;
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Details(int id)
        {
            var model = LibraryFacade.GetSong(id);
            if (model.Creator == UserFacade.GetGuidByEmail(User.Identity.Name))
            {
                model.Genres = LibraryFacade.GetGenreNames(model.Genres);
                return View("Details", model);
            }
            return RedirectToAction("Index");
        }
        
        public ActionResult Delete(int id)
        {
            var model = LibraryFacade.GetSong(id);
            if (model.Creator == UserFacade.GetGuidByEmail(User.Identity.Name))
            {
                LibraryFacade.DeleteSong(id);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            GetBasics();
            return View("Create", new SongDTO());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SongDTO model)
        {
            model.Creator = UserFacade.GetGuidByEmail(User.Identity.Name);
            if (ModelState.IsValid)
            {
                try
                {
                    model.Genres = LibraryFacade.FormGenres(model.Genres);
                    LibraryFacade.CreateSong(model);
                    return RedirectToAction("Index");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            GetBasics();
            return View("Create", model);
        }

        private void GetBasics()
        {
            AlbumFilter filter = new AlbumFilter
            {
                CreatorId = UserFacade.GetGuidByEmail(User.Identity.Name)
            };
            ArtistFilter filterA = new ArtistFilter
            {
                CreatorId = UserFacade.GetGuidByEmail(User.Identity.Name)
            };

            ViewBag.Albums = LibraryFacade.GetAlbumBasicsByFilter(filter);
            ViewBag.Artists = LibraryFacade.GetArtistBasicsByFilter(filterA);
        }

        public ActionResult Edit(int id)
        {
            var model = LibraryFacade.GetSong(id);
            if (model.Creator == UserFacade.GetGuidByEmail(User.Identity.Name))
            {
                GetBasics();
                model.Genres = LibraryFacade.GetGenreNames(model.Genres);
                return View("Edit", model);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SongDTO model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    model.Genres = LibraryFacade.FormGenres(model.Genres);
                    LibraryFacade.EditSong(model);
                    return RedirectToAction("Index");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return RedirectToAction("Edit", model);
        }


        private SongListViewModel InitNewSong(SongListQueryResultDTO result, SongFilter filter)
        {
            return new SongListViewModel()
            {
                Songs = 
                    new StaticPagedList<SongDTO>(result.ResultsPage, result.RequestedPage, LibraryFacade.PageSize, result.TotalResultCount),
                Filter = filter
            };
        }
    }
}

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello:) Music &lt;3</title>
    <link href="~/Content/style.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto&subset=latin,vietnamese' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="~/Scripts/script.js"></script>

</head>
<body>
<!--Main menu-->
    <div class="wrapper">
        <div id="menu_left">
            @User.Identity.Name
            <div class="menu_left_content">
                <a href="@Url.Action("Index","Home")">
                    <div class="menu_left_item" title="Home">
                        <i class="fa fa-home fa-lg"></i>&nbsp;&nbsp; Home
                    </div>
                </a>

                <a href="@Url.Action("Index", "Artist")">
                    <div class="menu_left_item" title="View artits">
                        <i class="fa fa-users fa-lg"></i>&nbsp;&nbsp; Artists
                    </div>
                </a>

                <a href="@Url.Action("Index", "Song")">
                    <div class="menu_left_item" title="View songs">
                        <i class="fa fa-play-circle fa-lg"></i>&nbsp;&nbsp; Songs
                    </div>
                </a>
                
                <a href="@Url.Action("Index", "Album")">
                    <div class="menu_left_item" title="View albums">
                        <i class="fa fa-circle fa-lg"></i>&nbsp;&nbsp; Albums
                    </div>
                </a>
                
                <a href="@Url.Action("Index", "Genre")">
                    <div class="menu_left_item" title="View genres">
                        <i class="fa fa-transgender fa-lg"></i>&nbsp;&nbsp; Genres
                    </div>
                </a>
                
                <a href="@Url.Action("Index", "Playlist")">
                    <div class="menu_left_item" title="View playlists">
                        <i class="fa fa-indent fa-lg"></i>&nbsp;&nbsp; Playlists
                    </div>
                </a>
                
                <a href="@Url.Action("Index", "Event")">
                    <div class="menu_left_item" title="View events">
                        <i class="fa fa-calendar fa-lg"></i>&nbsp;&nbsp; Events
                    </div>
                </a>

                <a href="@Url.Action("Settings", "Admin")">
                    <div class="menu_left_item" title="Settings">
                        <i class="fa fa-cog fa-lg"></i>&nbsp;&nbsp; Settings
                    </div>
                </a>
                
                <a href="@Url.Action("Propose", "Standart")">
                    <div class="menu_left_item" title="Settings">
                        <i class="fa fa-euro fa-lg"></i>&nbsp;&nbsp;&nbsp; Become VIP!
                    </div>
                </a>
                
                <a href="@Url.Action("Promote", "Admin")">
                    <div class="menu_left_item" title="Settings">
                        <i class="fa fa-user fa-lg"></i>&nbsp;&nbsp;&nbsp; Admin menu
                    </div>
                </a>

                @using (Html.BeginForm("Logout", "Account", FormMethod.Post, new { id = "logoutForm" }))
                {
                    @Html.AntiForgeryToken()
                    <a href="javascript:document.getElementById('logoutForm').submit()">
                        <div class="menu_left_item" title="Log out">
                            <i class="fa fa-sign-out fa-lg"></i>&nbsp;&nbsp; Log out
                        </div>
                    </a>
                }
            </div>
        </div>

        <div id="main_body">
            @RenderBody()
        </div>
    </div>

    <footer>
        &copy; @DateTime.Now.Year
    </footer>
</body>
</html>

PL/Views/Shared/_NoAuthLayout.cshtml
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log in</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <link rel='stylesheet' type='text/css' href="~/Content/noauthstyle.css">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto&subset=latin,vietnamese' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="script.js"></script>
</head>
<body>
    @RenderBody()
</body>
</html>