PL/Controllers/PlaylistController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using BL.DTO;
using BL.DTO.Playlist;
using BL.Facades;
using BL.Filters;
using BL.Utilities.AccountPolicy;
using Microsoft.Ajax.Utilities;
using PL.Models;
using X.PagedList;
using ActionResult = System.Web.Mvc.ActionResult;
using Controller = System.Web.Mvc.Controller;

namespace PL.Controllers
{
    [Authorize(Roles = Claims.Vips)]
    public class PlaylistController : Controller
    {
        private readonly string filterSessionKey = "filterartist";

        public LibraryFacade LibraryFacade { get; set; }
        public PremiumFacade PremiumFacade { get; set; }

        public UserFacade UserFacade { get; set; }

        public ActionResult Index(int page = 1)
        {
            PlaylistFilter filter = Session[filterSessionKey] as PlaylistFilter ?? new PlaylistFilter();

            PlaylistListQueryResultDTO result = LibraryFacade.GetPlaylists(filter, page);

            PlaylistListViewModel model = InitNewPlaylist(result, filter);

            return View("List", model);
        }

        [HttpPost]
        public ActionResult Index(PlaylistListViewModel model)
        {
            Session[filterSessionKey] = model.Filter;

            var result = LibraryFacade.GetPlaylists(model.Filter);

            var newModel = InitNewPlaylist(result, model.Filter);

            return View("List", newModel);
        }

        
        public ActionResult Rec(int id)
        {
            var result = new PlaylistListModel();
            result.Playlists = PremiumFacade.GetRecommendedPlaylists(LibraryFacade.GetPlaylist(id));
            return View("Rec", result);
        }

        public ActionResult ClearFilter()
        {
            Session[filterSessionKey] = null;
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Details(int id)
        {
            var model = LibraryFacade.GetPlaylist(id);
            List<string> genres = new List<string>();
            foreach (var s in model.Songs)
            {
                if (s.IsNullOrWhiteSpace()) continue;
                foreach (string g in LibraryFacade.GetSong(Convert.ToInt32(s)).Genres)
                {
                    if (!genres.Contains(g))
                    {
                        genres.Add(g);
                    }
                }
            }
            var res = LibraryFacade.GetGenreNames(genres);
            string result = "";
            foreach (var g in res)
            {
                result = g + ", ";
            }
            if (result.Length > 2)
            {
                result = result.Substring(0, result.Length - 2);
                ViewBag.Genres = result;
            }
            else
            {
                ViewBag.Genres = "";
            }
            InitBasics();
            if (model.Creator == UserFacade.GetGuidByEmail(User.Identity.Name))
            {
                return View("Details", model);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var model = LibraryFacade.GetPlaylist(id);
            if (model.Creator == UserFacade.GetGuidByEmail(User.Identity.Name))
            {
                LibraryFacade.DeletePlaylist(id);
            }
            InitBasics();
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            return View("Create", new PlaylistDTO());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PlaylistDTO model)
        {
            model.Creator = UserFacade.GetGuidByEmail(User.Identity.Name);
            if (ModelState.IsValid)
            {
                try
                {
                    LibraryFacade.CreatePlaylist(model);
                    return RedirectToAction("Index");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            InitBasics();
            return View("Create", model);
        }

        private void InitBasics()
        {
            var filter = new SongFilter
            {
                CreatorId = UserFacade.GetGuidByEmail(User.Identity.Name)
            };
            ViewBag.Songs = LibraryFacade.GetSongBasicsByFilter(filter);
        }

        public ActionResult Edit(int id)
        {
            var model = LibraryFacade.GetPlaylist(id);
            if (model.Creator == UserFacade.GetGuidByEmail(User.Identity.Name))
            {
                return View("Edit", model);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PlaylistDTO model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    LibraryFacade.EditPlaylist(model);
                    return RedirectToAction("Index");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return RedirectToAction("Edit", model);
        }


        private PlaylistListViewModel InitNewPlaylist(PlaylistListQueryResultDTO result, PlaylistFilter filter)
        {
            return new PlaylistListViewModel
            {
                Playlists = new StaticPagedList<PlaylistDTO>(result.ResultsPage, result.RequestedPage, LibraryFacade.PageSize, result.TotalResultCount),
                Filter = filter
            };
        }

        public ActionResult AddSong(int id)
        {
            ViewBag.Playlists = PremiumFacade.GetSelectedItems(UserFacade.GetGuidByEmail(User.Identity.Name));
            return View("Pick", new AddSongToPlaylistModel { IdSong = id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddSong(AddSongToPlaylistModel model)
        {
            if (ModelState.IsValid)
            {
                PremiumFacade.AddSongToPlaylist(model.Playlist, model.IdSong);
                return RedirectToAction("Index", "Song");
            }
            
            return View("Pick", model);
        }

        public ActionResult RemoveSong(int song, int playlist)
        {
            PremiumFacade.RemoveSongFromPlaylist(playlist, song);
            return RedirectToAction("Details", new {id = playlist});
        }

    }
}

PL/Controllers/SongController.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using BL.DTO;
using BL.DTO.Song;
using BL.Facades;
using BL.Filters;
using BL.Utilities.AccountPolicy;
using PL.Models;
using X.PagedList;

namespace PL.Controllers
{
    [Authorize(Roles = Claims.AuthenticatedUsers)]
    public class SongController : Controller
    {
        private readonly string filterSessionKey = "filtersong";

        public LibraryFacade LibraryFacade { get; set; }

        public UserFacade UserFacade { get; set; }

        public ActionResult Index(int page = 1)
        {
            SongFilter filter = Session[filterSessionKey] as SongFilter ?? new SongFilter();

            SongListQueryResultDTO result = LibraryFacade.GetSongs(filter, page);

            SongListViewModel model = InitNewSong(result, filter);

            return View("List", model);
        }


        [HttpPost]
        public ActionResult Index(SongListViewModel model)
        {
            Session[filterSessionKey] = model.Filter;

            var result = LibraryFacade.GetSongs(model.Filter);

            var newModel = InitNewSong(result, model.Filter);

            return View("List", newModel);
        }

        public ActionResult ClearFilter()
        {
            Session[filterSessionKey] = null;
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Details(int id)
        {
            var model = LibraryFacade.GetSong(id);
            if (model.Creator == UserFacade.GetGuidByEmail(User.Identity.Name))
            {
                model.Genres = LibraryFacade.GetGenreNames(model.Genres);
                return View("Details", model);
            }
            return RedirectToAction("Index");
        }
        
        public ActionResult Delete(int id)
        {
            var model = LibraryFacade.GetSong(id);
            if (model.Creator == UserFacade.GetGuidByEmail(User.Identity.Name))
            {
                LibraryFacade.DeleteSong(id);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            GetBasics();
            return View("Create", new SongDTO());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SongDTO model)
        {
            model.Creator = UserFacade.GetGuidByEmail(User.Identity.Name);
            if (ModelState.IsValid)
            {
                try
                {
                    model.Genres = LibraryFacade.FormGenres(model.Genres);
                    LibraryFacade.CreateSong(model);
                    return RedirectToAction("Index");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            GetBasics();
            return View("Create", model);
        }

        private void GetBasics()
        {
            AlbumFilter filter = new AlbumFilter
            {
                CreatorId = UserFacade.GetGuidByEmail(User.Identity.Name)
            };
            ArtistFilter filterA = new ArtistFilter
            {
                CreatorId = UserFacade.GetGuidByEmail(User.Identity.Name)
            };

            ViewBag.Albums = LibraryFacade.GetAlbumBasicsByFilter(filter);
            ViewBag.Artists = LibraryFacade.GetArtistBasicsByFilter(filterA);
        }

        public ActionResult Edit(int id)
        {
            var model = LibraryFacade.GetSong(id);
            if (model.Creator == UserFacade.GetGuidByEmail(User.Identity.Name))
            {
                GetBasics();
                model.Genres = LibraryFacade.GetGenreNames(model.Genres);
                return View("Edit", model);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SongDTO model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    model.Genres = LibraryFacade.FormGenres(model.Genres);
                    LibraryFacade.EditSong(model);
                    return RedirectToAction("Index");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return RedirectToAction("Edit", model);
        }


        private SongListViewModel InitNewSong(SongListQueryResultDTO result, SongFilter filter)
        {
            return new SongListViewModel()
            {
                Songs = 
                    new StaticPagedList<SongDTO>(result.ResultsPage, result.RequestedPage, LibraryFacade.PageSize, result.TotalResultCount),
                Filter = filter
            };
        }
    }
}

PL/Views/Song/Create.cshtml
@using System.Collections
@using System.Threading.Tasks
@using FormMethod = Microsoft.AspNetCore.Mvc.Rendering.FormMethod
@using SelectListItem = System.Web.Mvc.SelectListItem
@model BL.DTO.SongDTO
@{
    IEnumerable<SelectListItem> albums = ViewBag.Albums;
    IEnumerable<SelectListItem> artists = ViewBag.Artists;        
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.LabelFor(model => model.Name)<br />
    @Html.EditorFor(model => model.Name)<br />
    @Html.ValidationMessageFor(model => model.Name, "")
    <br />
    @Html.LabelFor(model => model.Artist)<br />
    @Html.DropDownListFor(model => model.ArtistPId, artists)<br />
    @Html.ValidationMessageFor(model => model.Artist, "", new { @class = "text-danger" })
    <br />
    @Html.LabelFor(model => model.Album)<br />
    @Html.DropDownListFor(model => model.AlbumPId, albums)<br />
    @Html.ValidationMessageFor(model => model.Album, "", new { @class = "text-danger" })
    <br />
    @Html.LabelFor(model => model.Length)<br />
    @Html.EditorFor(model => model.Length)<br />
    @Html.ValidationMessageFor(model => model.Length, "", new { @class = "text-danger" })
    <br/>
    @Html.LabelFor(model => model.Genres)<br />
    <div class="genreFields">
        <div class="button" onclick="addGenreField()" style ="width:300px">Add More Fields</div>
        @if (@Model.Genres != null)
        {
            foreach (var genre in Model.Genres)
            {
                <div>
                    <input type="text" id="Genres" name="Genres" value="@genre">
                    <a href="#" class="remove_field">Remove</a>
                </div>
            }
        }
        <div><input type="text" class="Genres" name="Genres" ></div>
    </div>
    @Html.ValidationMessageFor(model => model.Genres, "", new { @class = "text-danger" })



    <br/>

    <input type="submit" value="Create" class="button" />

}
<br /><br />
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PL/Views/Song/Details.cshtml
@using BL.Facades
@model BL.DTO.SongDTO

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    <a href="@Url.Action("Edit", new {id = Model.ID})"><input type="submit" class="button" value="Edit" /></a>
    <a href="@Url.Action("Index")"><input type="submit" class="button" value="Back to List" /></a>
</p>
<div>
    <hr />
    <h1>
        @Html.DisplayFor(model => model.Name)
    </h1>

    <h2>@Html.DisplayNameFor(model => model.Album)</h2>
    <p>
        <a href="../../Album/Details/@Html.DisplayFor(model => model.AlbumPId)">@Html.DisplayFor(model => model.Album.Name)</a>
    </p>
    <h2>@Html.DisplayNameFor(model => model.Length)</h2>
    <p>
        @Html.DisplayFor(model => model.Length)
    </p>
    <h2>@Html.DisplayNameFor(model => model.Artist)</h2>
    <p>
        <a href="../../Artist/Details/@Html.DisplayFor(model => model.ArtistPId)">@Html.DisplayFor(model => model.Artist.Name)</a>  
    </p>
    <h2>@Html.DisplayNameFor(model => model.Genres)</h2>
    <p>
        @foreach (string genre in Model.Genres)
        {
            @Html.Raw(genre + " | ");
        }
    </p> 
    <br />
</div>

PL/Views/Song/Edit.cshtml
@using System.Collections
@using System.Threading.Tasks
@using System.Web.UI.WebControls
@using BL.DTO
@using BL.DTO.Album
@using BL.Facades
@using FormMethod = Microsoft.AspNetCore.Mvc.Rendering.FormMethod
@using SelectListItem = System.Web.Mvc.SelectListItem
@model BL.DTO.SongDTO
@{
    IEnumerable<SelectListItem> albums = ViewBag.Albums;
    IEnumerable<SelectListItem> artists = ViewBag.Artists;
    ViewBag.Title = "Edit song";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Creator)
    @Html.HiddenFor(model => model.ID)
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.LabelFor(model => model.Name)<br />
    @Html.EditorFor(model => model.Name)<br />
    @Html.ValidationMessageFor(model => model.Name, "")
    <br />
    @Html.LabelFor(model => model.Artist)<br />
    @Html.DropDownListFor(model => model.ArtistPId, artists)<br />
    @Html.ValidationMessageFor(model => model.Artist, "", new { @class = "text-danger" })
    <br />
    @Html.LabelFor(model => model.Album)<br />
    @Html.DropDownListFor(model => model.AlbumPId, albums)<br />
    @Html.ValidationMessageFor(model => model.Album, "", new { @class = "text-danger" })
    <br />
    @Html.LabelFor(model => model.Length)<br />
    @Html.EditorFor(model => model.Length)<br />
    @Html.ValidationMessageFor(model => model.Length, "", new { @class = "text-danger" })
    <br />
    @Html.LabelFor(model => model.Genres)<br />
    <div class="genreFields">
        <div class="button" onclick="addGenreField()" style="width:300px">Add More Fields</div>
        @if (@Model.Genres != null)
        {
            foreach (var genre in Model.Genres)
            {
                <div>
                    <input type="text" id="Genres" name="Genres" value="@genre">
                    <a href="#" class="remove_field">Remove</a>
                </div>
            }
        }
        <div><input type="text" id="Genres" name="Genres"></div>
    </div>
    @Html.ValidationMessageFor(model => model.Genres, "", new { @class = "text-danger" })

    <input type="submit" value="Edit" class="button" />

}
<br /><br />
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PL/Views/Song/List.cshtml
@model PL.Models.SongListViewModel
@using System.Web.Mvc.Html
@using X.PagedList.Mvc
@{
    bool useCustomBackground = false;
}
<p>
    <a href="@Url.Action("Create")">
        <input type="submit" class="button" value="Create New" />
    </a>
</p>
<div class="filter">
    @using (Html.BeginForm())
    {
        <p>Name: </p>
        @Html.EditorFor(model => model.Filter.Name)
        <br/><br/>
        <p>Artist name: </p>
        @Html.EditorFor(model => model.Filter.ArtistName)
        <p>Album name: </p>
        @Html.EditorFor(model => model.Filter.AlbumId)
        <br />
        <br />
        <a type="button" class="button" href='@Url.Action("ClearFilter")'>Clear</a>
        <button class="button" type="submit">Filter</button>
        <hr />
    }
    @Html.PagedListPager(Model.Songs, page => Url.Action("Index", new { page }))
    <br />
</div>
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Artist
        </th>
        <th>
            Album
        </th>
        <th>
            Length
        </th>
    </tr>
    @foreach (var item in Model.Songs)
    {
        {
            useCustomBackground = !useCustomBackground;
        }
        <tr class="@(useCustomBackground ?  "tr_background" : "")">
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a href="../Artist/Details/@Html.DisplayFor(modelItem => item.ArtistPId)">@Html.DisplayFor(modelItem => item.Artist.Name)</a>
            </td>
            <td>
                <a href="../Album/Details/@Html.DisplayFor(modelItem => item.AlbumPId)">@Html.DisplayFor(modelItem => item.Album.Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Length)
            </td>
            <td>
                <a href="@Url.Action("Edit", new {id = item.ID})">
                    <div class="button button-table">
                        <i class="fa fa-pencil-square-o fa-lg"></i>
                    </div>
                </a>
            </td>
            <td>
                <a href="@Url.Action("Delete", new {id = item.ID})">
                    <div class="button button-table">
                        <i class="fa fa-trash-o fa-lg"></i>
                    </div>
                </a>
            </td>
            <td>
                <a href="@Url.Action("Details", new {id = item.ID})">
                    <div class="button button-table">
                        <i class="fa fa-ellipsis-h fa-lg"></i>
                    </div>
                </a>
            </td>
            <td>
                <a href="@Url.Action("AddSong", "Playlist", new {id = item.ID})">
                    <div class="button button-table" title="Add song to playlist">
                        <i class="fa fa-plus fa-lg"></i>
                    </div>
                </a>
            </td>
        </tr>
    }
</table>